### ISSUE TITLE
can I specify base url to router?

### ISSUE THREAD

**Issue by zhaoyao91** [pebble/koa-joi-router#1]
this router is cool, but i want to add base url to the router so i can use it like this:

var pub = routuer({baseUrl:'/test'});
pub.post('/wow', ...);

then url '/test/wow' can be visited

can this be possible by some ways?

3q

**Comment by reyawn** [comment]
Check out [koa-resourcer](https://github.com/pebble/koa-resourcer), it uses koa-joi-router behind-the-scenes and provides a framework for "mounting" on paths.
