### ISSUE TITLE
How do I multipart?

### ISSUE THREAD

**Issue by vyooTeam** [pebble/koa-joi-router#2]
Hello everyone,
I saw the docs and I have managed to successfully receive every type of requests except for multipart..

I copied the given code:
``admin.route({
  method: 'post'
, path: '/blog'
, validate: { type: 'multipart' }
, handler: function *(){
    var parts = yield this.request.parts
    var part

    while (part = yield parts) {
      // do something with the incoming part stream
      part.pipe(someOtherStream)
    }

    console.log(parts.field.name) // form data
  }
})``

But when I run my server I immediatly get the following error:
TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"

If I use co-busboy myself meaning:
``
    var parts = parse(this)
    var part
    while (part = yield parts) {
      console.log (part);
      if (part.length) {
        // arrays are busboy fields
        console.log('key: ' + part[0])
        console.log('value: ' + part[1])
      } else {
        // otherwise, it's a stream
        part.pipe(fs.createWriteStream('some file.txt'))
      }
    }
``
It works amazingly perfect

I know it has something to do with generators but don't get why..
Also - am I supposed to validate the fields myself? because I can't do:
``validate: {
	type: 'multipart',
	body: {
	  username: Joi.string().required(),
	  email: Joi.string().optional()
	}
}``

Din.

**Comment by aheckmann** [comment]
1) the best way to help debug is to post a file we can run to reproduce the issue
2) "can you validate multipart fields?" - interesting idea. no, this is not currently supported. `parts` is simply an untouched co-busboy object

**Comment by aheckmann** [comment]
closing, no response
